In [2]:
!pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.5.20)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [6]:
url = "https://books.toscrape.com/"

response = requests.get(url)

print(response.status_code)

200

In [8]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Website URL
url = "https://books.toscrape.com/"

# Get page content
response = requests.get(url)

# Parse HTML
soup = BeautifulSoup(response.text, "html.parser")

# Find all books on first page
books = soup.find_all("article", class_="product_pod")

# Store data
data = []

for book in books:
    title = book.h3.a["title"]
    price = book.find("p", class_="price_color").text
    rating = book.find("p", class_="star-rating")["class"][1]
    availability = book.find_all("p")[1].text.strip()

    data.append({
        "Title": title,
        "Price": price,
        "Rating": rating,
        "Availability": availability
    })

# Create DataFrame
df = pd.DataFrame(data)

# Show first page data
df

,Title,Price,Rating,Availability
0,A Light in the Attic,Â£51.77,Three,Â£51.77
1,Tipping the Velvet,Â£53.74,One,Â£53.74
2,Soumission,Â£50.10,One,Â£50.10
3,Sharp Objects,Â£47.82,Four,Â£47.82
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,Â£54.23
5,The Requiem Red,Â£22.65,One,Â£22.65
6,The Dirty Little Secrets of Getting Your Dream...,Â£33.34,Four,Â£33.34
7,The Coming Woman: A Novel Based on the Life of...,Â£17.93,Three,Â£17.93
8,The Boys in the Boat: Nine Americans and Their...,Â£22.60,Four,Â£22.60
9,The Black Maria,Â£52.15,One,Â£52.15
10,"Starving Hearts (Triangular Trade Trilogy, #1)",Â£13.99,Two,Â£13.99
11,Shakespeare's Sonnets,Â£20.66,Four,Â£20.66
12,Set Me Free,Â£17.46,Five,Â£17.46
13,Scott Pilgrim's Precious Little Life (Scott Pi...,Â£52.29,Five,Â£52.29
14,Rip it Up and Start Again,Â£35.02,Five,Â£35.02
15,Our Band Could Be Your Life: Scenes from the A...,Â£57.25,Three,Â£57.25
16,Olio,Â£23.88,One,Â£23.88
17,Mesaerion: The Best Science Fiction Stories 18...,Â£37.59,One,Â£37.59
18,Libertarianism for Beginners,Â£51.33,Two,Â£51.33
19,It's Only the Himalayas,Â£45.17,Two,Â£45.17

In [10]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

data = []

# Loop through all 50 pages
for page in range(1, 51):

    if page == 1:
        url = "https://books.toscrape.com/"
    else:
        url = f"https://books.toscrape.com/catalogue/page-{page}.html"

    response = requests.get(url)

    if response.status_code != 200:
        print(f"Failed to load page {page}")
        continue

    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    for book in books:
        title = book.h3.a["title"]
        price = book.find("p", class_="price_color").text
        rating = book.find("p", class_="star-rating")["class"][1]

        availability = book.find(
            "p",
            class_="instock availability"
        ).text.strip()

        data.append({
            "Title": title,
            "Price": price,
            "Rating": rating,
            "Availability": availability
        })

    print(f"Page {page} scraped successfully")

# Create DataFrame
df = pd.DataFrame(data)

print(f"\nTotal Books Scraped: {len(df)}")

# Display data
df

Page 1 scraped successfully
Page 2 scraped successfully
Page 3 scraped successfully
Page 4 scraped successfully
Page 5 scraped successfully
Page 6 scraped successfully
Page 7 scraped successfully
Page 8 scraped successfully
Page 9 scraped successfully
Page 10 scraped successfully
Page 11 scraped successfully
Page 12 scraped successfully
Page 13 scraped successfully
Page 14 scraped successfully
Page 15 scraped successfully
Page 16 scraped successfully
Page 17 scraped successfully
Page 18 scraped successfully
Page 19 scraped successfully
Page 20 scraped successfully
Page 21 scraped successfully
Page 22 scraped successfully
Page 23 scraped successfully
Page 24 scraped successfully
Page 25 scraped successfully
Page 26 scraped successfully
Page 27 scraped successfully
Page 28 scraped successfully
Page 29 scraped successfully
Page 30 scraped successfully
Page 31 scraped successfully
Page 32 scraped successfully
Page 33 scraped successfully
Page 34 scraped successfully
Page 35 scraped successfully
Page 36 scraped successfully
Page 37 scraped successfully
Page 38 scraped successfully
Page 39 scraped successfully
Page 40 scraped successfully
Page 41 scraped successfully
Page 42 scraped successfully
Page 43 scraped successfully
Page 44 scraped successfully
Page 45 scraped successfully
Page 46 scraped successfully
Page 47 scraped successfully
Page 48 scraped successfully
Page 49 scraped successfully
Page 50 scraped successfully

Total Books Scraped: 1000

,Title,Price,Rating,Availability
0,A Light in the Attic,Â£51.77,Three,In stock
1,Tipping the Velvet,Â£53.74,One,In stock
2,Soumission,Â£50.10,One,In stock
3,Sharp Objects,Â£47.82,Four,In stock
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock
...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,Â£55.53,One,In stock
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Â£57.06,Four,In stock
997,A Spy's Devotion (The Regency Spies of London #1),Â£16.97,Five,In stock
998,1st to Die (Women's Murder Club #1),Â£53.98,One,In stock
999,"1,000 Places to See Before You Die",Â£26.08,Five,In stock

In [12]:
df.to_csv("all_books.csv", index=False)

print("CSV file created successfully!")

CSV file created successfully!

In [14]:
from google.colab import files

files.download("all_books.csv")

In [16]:
df.to_csv("all_books.csv", index=False)

from google.colab import files
files.download("all_books.csv")